### ISSUE TITLE
New block in BackOffice is  not showing up

### ISSUE THREAD

**Issue by aimeric** [BeHappyCommunication/sylius-invoice#1]
Hi, 

I'm using Sylius 1.1.0-DEV , I have install and configure your bundle, but the new block in BackOffice and the new button in customer's account are not showing up.

**config.yml**

```
imports:
    - { resource: '@BehappyInvoicePlugin/Resources/config/app/config.yml' }

twig:
    paths:
        '%kernel.project_dir%/vendor/behappy/invoice-plugin/src/Resources/views': BehappyInvoice
```

**routing.yml**

```
behappy_invoice_admin:
    resource: "@BehappyInvoicePlugin/Resources/config/app/routing_admin.yml"
    prefix: /admin

behappy_invoice_shop:
    resource: "@BehappyInvoicePlugin/Resources/config/app/routing_shop.yml"
    prefix: /{_locale}/account
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
```

Do you can any idea how to fix this issue ?
